import json
from pathlib import Path
from datetime import datetime

def generate_report(session_id: str, log_dir: str = "logs") -> str:
    """
    Reads the JSONL log for a session and produces a markdown audit report.
    Returns the report as a string.
    """
    log_path = Path(log_dir) / f"session_{session_id}.jsonl"
    if not log_path.exists():
        return f"No log found for session {session_id}"

    events = []
    with open(log_path) as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    events.append(json.loads(line))
                except json.JSONDecodeError:
                    pass

    return _format_report(session_id, events)


def _format_report(session_id: str, events: list[dict]) -> str:
    lines = []
    lines.append(f"# Vigil Session Report — {session_id}")
    lines.append("")

    # Session metadata
    start_event = next((e for e in events if e.get("event") == "session_start"), None)
    if start_event:
        lines.append(f"**Started:** {start_event.get('timestamp', 'unknown')}")
    lines.append("")

    # Brief preview
    brief_event = next((e for e in events if e.get("event") == "brief_generated"), None)
    if brief_event:
        lines.append("## Architecture Brief (Preview)")
        lines.append(f"```")
        lines.append(brief_event.get("brief_preview", "")[:500])
        lines.append(f"```")
        lines.append("")

    # Tool call summary
    tool_calls = [e for e in events if e.get("event") == "tool_call"]
    if not tool_calls:
        lines.append("No tool calls recorded.")
        return "\n".join(lines)

    # Stats
    total = len(tool_calls)
    blocked = [e for e in tool_calls if e.get("verdict") in ("BLOCK", "CLEAR_BLOCK")]
    approved = [e for e in tool_calls if e.get("verdict") in ("APPROVE", "CLEAR_PASS")]
    ambiguous = [e for e in tool_calls if e.get("verdict") == "AMBIGUOUS"]
    skipped = [e for e in tool_calls if e.get("verdict") == "SKIP"]
    malformed = [e for e in tool_calls if e.get("malformed_intent")]

    lines.append("## Summary")
    lines.append(f"| Metric | Count |")
    lines.append(f"|---|---|")
    lines.append(f"| Total tool calls | {total} |")
    lines.append(f"| Approved | {len(approved)} |")
    lines.append(f"| Blocked | {len(blocked)} |")
    lines.append(f"| Ambiguous (Tier 2 routed) | {len(ambiguous)} |")
    lines.append(f"| Skipped (not security relevant) | {len(skipped)} |")
    lines.append(f"| Malformed INTENT (inferred) | {len(malformed)} |")
    lines.append("")

    # Findings (BLOCK only)
    if blocked:
        lines.append("## Security Findings")
        lines.append("")
        for e in blocked:
            lines.append(f"### Call #{e.get('call_id', '?')} — {e.get('verdict')} ({e.get('severity', 'UNKNOWN')})")
            lines.append(f"**File:** `{e.get('file', 'unknown')}`")
            lines.append(f"**Tool:** {e.get('tool', 'unknown')}")
            intent = e.get("intent", {})
            lines.append(f"**Intent:** {intent.get('intent', '-')}")
            lines.append(f"**Finding:** {e.get('finding', 'No details')}")
            if e.get("fix"):
                lines.append(f"**Fix:** {e['fix']}")
            if e.get("invariant_violated"):
                lines.append(f"**Invariant violated:** `{e['invariant_violated']}`")
            lines.append(f"**Timestamp:** {e.get('timestamp', '-')}")
            lines.append("")

    # Malformed INTENT summary
    malformed_events = [e for e in events if e.get("event") == "malformed_intent"]
    if malformed_events:
        lines.append("## Malformed INTENT Signals")
        lines.append("")
        lines.append("These calls had empty or garbage INTENT fields. Security relevance was inferred from the diff.")
        lines.append("")
        for e in malformed_events:
            lines.append(f"- Call #{e.get('call_id')}: `{e.get('file', '-')}` — {e.get('reason', '-')}")
        lines.append("")

    # Invariant status
    invariant_violations = set(
        e.get("invariant_violated")
        for e in tool_calls
        if e.get("invariant_violated")
    )
    if invariant_violations:
        lines.append("## Invariant Violations")
        for inv in sorted(invariant_violations):
            lines.append(f"- ❌ `{inv}`")
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by Vigil at {datetime.utcnow().isoformat()}*")

    return "\n".join(lines)
