from pydantic import BaseModel


class SecurityInvariant(BaseModel):
    id: str              # short slug, e.g. "no-pii-in-logs", "admin-role-required"
    description: str     # human-readable assertion that must always hold
    satisfied: bool = True  # flipped to False when a BLOCK references this invariant


class TrustBoundary(BaseModel):
    label: str           # "PUBLIC" | "AUTHENTICATED" | "INTERNAL ONLY"
    patterns: list[str]  # route patterns, e.g. ["/api/v1/checkout", "/api/v1/products"]


class ArchitectureBrief(BaseModel):
    system_purpose: str
    trust_boundaries: list[TrustBoundary]
    auth_model: str
    data_flows: list[str]
    invariants: list[SecurityInvariant]
    sensitive_operations: list[str]
    raw_markdown: str = ""  # full markdown brief as generated by the Phase 1 reasoning model
